language: c
os:
    - linux

env:
  global:
    - GOPATH=~
    - DOTPATH=~/.dotfiles

install:
    - curl -L raw.githubusercontent.com/sfus/dotfiles/master/etc/install | bash

before_script:
    - cd $(dotpath)

script:
    - make --silent test
